### ISSUE TITLE
non-competitive type

### ISSUE THREAD

**Issue by ColinRobbins** [ColinRobbins/scm-helper#55]
**Is your feature request related to a problem? Please describe.**
in the entity types, would it be possible to support non-competitive? eg.

**Describe the solution you'd like**
```
non-competitive:
    name: "Learn to Swim swimmers"
    check_se_number: False
    parents: True
```
